services:
  db:
    image: postgres:15-alpine
    container_name: my_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.docker
    ports:
      - "5432:5432" # Mở port này để có thể kết nối từ bên ngoài nếu cần
    restart: unless-stopped

  app:
    build: .
    # The default command to run when the container starts.
    # This will be passed to entrypoint.sh
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: my_fastapi_app
    volumes:
      - ./app:/app/app # Mount mã nguồn để auto-reload hoạt động
    ports:
      - "8000:8000"
    env_file:
      - ./.env.docker
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
